### ISSUE TITLE
How to add my own json ??

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [p32929/HouseAds2#1]
hi i am trying to add this library in my app but i wondering how to add all my custom url JSON pls help me here

**Comment by p32929** [comment]
You can create a public repository in github/gitlab and put a json file in the repository. You need to use the raw url(See the screenshot) of that json file. Hope it helps.
![Screenshot (26)](https://user-images.githubusercontent.com/6418354/63734853-babfd480-c89f-11e9-9c58-aab0f4300f2c.png)
