### ISSUE TITLE
NOt working!

### ISSUE THREAD

**Issue by IhaYarre** [p32929/HouseAds2#2]
Interstitial nor banner are showing 
![image](https://user-images.githubusercontent.com/34599417/73464887-da43b780-437f-11ea-9ed7-24fd3b2dfd8d.png)

**Comment by p32929** [comment]
Could you also share the code? Just by screenshot we cannot determine the error

**Comment by IhaYarre** [comment]
> 
> 
> Could you also share the code? Just by screenshot we cannot determine the error

thanks, I figure out it.
