### ISSUE TITLE
Exit Button

### ISSUE THREAD

**Issue by IhaYarre** [p32929/HouseAds2#3]
how to prevent the app from exiting when clicking on the EXIT button on the interstitial?

**Comment by p32929** [comment]
The whole point of the exit button is to exit the app. why should we need to prevent it?

**Comment by IhaYarre** [comment]
OK 
but sometimes i don't need to exit the app i just want to close the Intertitial Ad...

**Comment by p32929** [comment]
oww, in that case, you might have to fork the repo and add your own logic to it. I'm not sure about the use cases
