### ISSUE TITLE
autoChangeBannerAds() causes app crash when used offline

### ISSUE THREAD

**Issue by compusciking** [p32929/HouseAds2#5]
peace be upon you bro
autoChangeBannerAds(seconds) causes app crash when used offline!

**Comment by p32929** [comment]
Okay, I'll take a look at the problem today. Thanks for informing me

**Comment by p32929** [comment]
Fixed the issue. Now try with this:
`implementation 'com.github.p32929:HouseAds2:1.0.0.16'`

Feel free to let me know if you see any more bugs.
